{{- if .Values.interpolation.pvc.create -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.interpolation.pvc.name }}
  namespace: {{ .Values.interpolation.pvc.namespace }}
  annotations:
    {{- range $key, $value := .Values.interpolation.pvc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  storageClassName: {{ .Values.interpolation.pvc.storageclass.name }}
  accessModes:
    - {{ .Values.interpolation.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.interpolation.pvc.storage }}
{{- end -}}
